### ISSUE TITLE
gestione utenti: impedire suicidio di admin

### ISSUE THREAD

**Issue by alfcar62** [alfcar62/OSMGB#15]
Gestione utenti: Deve essere impedito all'utente admin di eliminare se stesso

**Comment by FerraiuoloP** [comment]
fixes #15 La modifica l'avevo effettuata la settimana scorsa sul git vecchio (insieme alla conferma eliminazione utente e la colonna "abitanti" in case) e la versione master del progetto principale ha già queste modifiche perchè l'aveva mergiata in automatico con il suo progetto. @alfcar62

**Comment by alfcar62** [comment]
Non funziona più l'inserimento di un nuovo utente.
Probabilmente la modifica che hai apportato ha comportato nuovi errori.
Prova a vedere come mai
