### ISSUE TITLE
ritorno da paginazione (gestione case)

### ISSUE THREAD

**Issue by alfcar62** [alfcar62/OSMGB#30]
Dalla videata elenco case (gest_case.php) se si entra nel dettaglio (ad es in modifica), quando si ritorna alla videata con l'elenco, si perde il riferimento alla pagina nella quale si era. Si tratta di usare i cookies o le sessioni e memorizzare la pagina corrente....

**Comment by alfcar62** [comment]
Non funziona ! Hai provato?
Questo l'errore:  Undefined index: pag_m in C:\xampp\htdocs\OSM\Anagrafe\morance\modifica_moranca.php on line 14

Inoltre metti a posto l'indentazione.

**Comment by GDennis01** [comment]
L'errore in modifica moranca non compare. Forse ha provato ad accedere a modifica moranca direttamente senza passare prima da gest morance?

**Comment by alfcar62** [comment]
Ok. in effetti mi capita in localhost e non su test. Cerco di capire.Grazie. Ciao
