### ISSUE TITLE
paginazione a volte fa vedere più pagine di quelle che servono

### ISSUE THREAD

**Issue by alfcar62** [alfcar62/OSMGB#33]
Ho notato che la query che determina il n. di record ritorna un n. diverso dal n. di record della query che visualizza i dati. Questo determina a volte che si vada a finire in una pagina che non ha dati da visualizzare.
Verificare su gest_persone.php, gest_case.php e gest_morance.php.

**Comment by GDennis01** [comment]
Ho provato la modifica sulla versione attuale e non ho riscontrato nessun errore

**Comment by alfcar62** [comment]
ok!  Grazie.

**Comment by alfcar62** [comment]
Ho visto che la paginazione in alcune situazioni sbaglia il calcolo della pagina corrente.
Es: da elenco persone,  vai alla pagina 20, poi cambi l'opzione e scegli la visualizzazione dei deceduti, la query parte dalla pagina sbagliata.
Lo stesso succede se cambi la zona (se prima scegli tutte le zone, vai all'ultima pagina e poi cambi scegliendo ad es: la zona Nord.
Il problema è che la variabile $first nella query rimane quella della pagina letta precedentemente, e se cambi il filtro di ricerca, questo non sempre va bene.
Puoi verificare  se è possibile sistemare? 
La funzione di paginazione non è molto semplice da comprendere....magari tu che l'hai scritta riesci.
Ciao

**Comment by alfcar62** [comment]
Sistemato, almeno per persone
