### ISSUE TITLE
report persone: Export persone in file persone .xls 

### ISSUE THREAD

**Issue by scursa** [alfcar62/OSMGB#42]

**Comment by alfcar62** [comment]
Mi sembra un ottimo lavoro. Non ho guardato ancora il codice ma l'ho provato e mi sembra ok.
Volevo chiederti alcune piccole modifiche:
1) All'inizio del file (xls o xlsx?) , una intestazione che indichi
 - la fonte del dato: Anagrafe Web  
 - la data in cui è stato fatto
 - il tipo di report effettuato (basta indicare i criteri di ricerca)

2)  Nel filtro di ricerca 
  - la zona deve pescarla dal DB (zona.desc)  e quindi diventa maiuscola
  - "tutte" e non "tutto"
  - SELEZIONARE IL SESSO': "tutti" invece di "maschi e femmine"
  - SELEZIONARE LE ETA': aggiungere  "tutti"  oltre a  "maggiorenni" e "minorenni"
  - Nome del file da scaricare  aggiungere .xls al fondo
 
3) SELEZIONARE L'ORDINE  diventa ORDINAMENTO  IN BASE A:  nome/età/identificativo 

Penso siano modifiche abbastanza semplici. Mi pare un buon lavoro.
