### ISSUE TITLE
elenco morance: cliccare sulla foto per visualizzare la foto della moranca

### ISSUE THREAD

**Issue by alfcar62** [alfcar62/OSMGB#48]
elenco morance: cliccare sulla foto per visualizzare la foto della moranca

Nell'elenco delle morance(gest_morance.php) si chiede di poter cliccare sulla foto della morancae visualizzarla in una nuova finestra  (non a tutto schermo ma abbastanza grande da poterla vedere)

**Comment by alfcar62** [comment]
Se provi su ntchanguetest la foto si zoomma, però non viene visualizzata al centro come per le case, ma va a sovrapporsi in alto a sinistra. Hai idea come mai?

**Comment by FerraiuoloP** [comment]
Su ntchanguetest manca il file gest_morance_temp_css.css,se vuole posso aggiungerlo io @alfcar62
