### ISSUE TITLE
bug: carica foto non funziona per file con estensione .jpg

### ISSUE THREAD

**Issue by alfcar62** [alfcar62/OSMGB#83]
in modifica e inserimento morance e case, se si carica la foto in formato jpg, la foto non viene caricata.

**Comment by FerraiuoloP** [comment]
Ho fatto dei test con diverse immagini .jpg e non ho riscontrato nessun errore.Se può dirmi l'errore che viene presentato(sopra a "Seleziona foto da caricare") posso cercare di risolvere

**Comment by alfcar62** [comment]
strano, l'errore lo dava  a Salvatore che ha provato da casa a caricare un
file JPG. Quando gli ho detto di rinominarlo in jpeg ha funzionato.
Provo anche io e ti faccio sapere.
Il Sab 18 Apr 2020, 10:54 FerraiuoloP <notifications@github.com> ha scritto:

**Comment by alfcar62** [comment]
Probabilmente Salvatore ha fatto qualche errore. Anche a me funziona
