### ISSUE TITLE
log attività di login su tabella che non cresce all'infinito

### ISSUE THREAD

**Issue by alfcar62** [alfcar62/OSMGB#85]
Il log delle attività di login (tabella login_logs) non deve crescere all'infinito.
SI può mantenere l'attività dell'ultimo mese oppure si decide che al massimo si possono avere ad esempio 100 righe.
Le righe eccedenti più vecchie vengono cancellate.

**Comment by FerraiuoloP** [comment]
Su login_logs vengono salvati anche i tentativi di accesso falliti per cui ho pensato alla seguente soluzione(già provata ad implementare e funzionante): 
-Eliminare dopo 1 giorno tutti i tentativi falliti di login.
-Eliminare dopo 1 mese tutti i tentativi riusciti di login.
Per capire se il login è andato a buon fine ho aggiunto un attributo(foreign key di user) a login_logs che risulta null in caso di login fallito oppure ha al suo interno il nome dell'utente in caso di login riuscito.Se le va bene posso caricarle la nuova tabella login_logs e il file login.php modificato

**Comment by FerraiuoloP** [comment]
Ho anche aggiunta un attributo data di tipo DATETIME a login_logs risolvendo anche l'issue #22

**Comment by alfcar62** [comment]
ciao.
Ok x il date time.
Mi sembra strano che se metti una FK puoi inserire null. La FK richiede la
presenza di un valore che fa riferimento ad una PK sulla tabella esterna.
Sei sicuro che funzioni? Sul discorso 1 giorno, 1 mese, va bene. Cerca di
rendere facilmente confifurabi quei valori, ad es ,usando una costante
all'inizio del codice PHP.
 Quando completi la modifica  puoi fare la pull request con il nuovo file
login
PHP e lo script di alter tale sulla tabella login_logs da modificare.

Ti ringrazio, buon lavoro

Il Sab 18 Apr 2020, 10:49 FerraiuoloP <notifications@github.com> ha scritto:
