### ISSUE TITLE
statistiche per età fertile

### ISSUE THREAD

**Issue by alfcar62** [alfcar62/OSMGB#97]
Da rivedere il codice. Non è generalizzato. Si deve fare il calcolo dell'età e poi farne la statistica.
L'età fertile delle donne è compresa tra 13 e 40 anni.
Non capisco cosa sia questo codice:
where persone.sesso='f' and zone.NOME='$zona' and DATEDIFF('$oraoggi',data_nascita)>5475 and DATEDIFF('$oraoggi',data_nascita)<16425

**Comment by arne-ale** [comment]
consegnata la scorsa settimana,errore nel commento per chiuderla
